branches:
  - main

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
      changelogTitle: "# ØKP4 Contract schema"
  - - "@semantic-release/npm"
    - npmPublish: false
      tarballDir: "false"
      pkgRoot: ./ts/cognitarium-schema
    - npmPublish: false
      tarballDir: "false"
      pkgRoot: ./ts/law-stone-schema
    - npmPublish: false
      tarballDir: "false"
      pkgRoot: ./ts/objectarium-schema
  - "@semantic-release/github"
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - ts/cognitarium-schema/package.json
        - ts/law-stone-schema/package.json
        - ts/objectarium-schema/package.json
      message: "chore(release): perform release ${nextRelease.version}"
